### ISSUE TITLE
Create and Edit data

### ISSUE THREAD

**Issue by fluxboost** [snipcart/wordpress-rest-api-react#8]
Hi there!

I'm an iOS/Flutter Developer contractor and I'm trying to find out if it's possible to turn a WordPress Web App (using Advanced Custom Fields etc.) into a Mobile App using the WordPress API.

So far it seems perfectly possible to get all the data I need, but I can't seem to figure out if I'm able to create/edit existing custom data using the WordPress API with authentication involved.

Any insight into whether it is possible would be greatly appreciated.

Thanks,
Harry

**Comment by JeanSebTr** [comment]
Hi @fluxboost !

I'd suggest asking on forums specialized on WP or on Stackoverflow. We're not familiar with the editing capabilities of the Wordpress API.
